web:
  build: .
  ports:
    - '80:80'
  links:
    - db:db
  volumes:
    - '.:/var/www/html'

db:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1

composer:
  image: composer/composer:php5
  volumes:
    - '.:/app'
